### ISSUE TITLE
Problem with clean installation of OpenCATS 0.9.4 version (php5.5)

### ISSUE THREAD

**Issue by Albin4d** [opencats/OpenCATS#264]
Hi Guys,

I want to instal new version of (clean instal - not upgrade) Opencats 0.9.4 but following message appear:

Parse error: syntax error, unexpected '[' in /home/xxxxx/domains/xxxxxx.xx/public_html/OpenCATS/lib/ACL.php on line 61

I've changed my domain name and user ty "xxx" for privacy reasons.
Can someone help me wit thi issue?

It's strange as I had no problems with 0.9.3-3 version installation.

**Comment by skrchnavy** [comment]
Hi.

What version of PHP is installed in your system?

this is code on line 61:
```
        if( NULL !== ACCESS_LEVEL_MAP[$userCategory][$securedObjectName])
```
Please check your config.php if you don't have there ACCESS_LEVEL_MAP not inside comment block.

**Comment by Albin4d** [comment]
As i can see in my directAdmin Panel its version 5.5 - should I change it to other?

in config file i have something like that:

// defining access levels different from the default access level    
const ACCESS_LEVEL_MAP = array(
        'candidate' => array(
        ),
        'demo' => array(
            'candidates' => ACCESS_LEVEL_DELETE,
            'candidates.emailCandidates' => ACCESS_LEVEL_DISABLED,
            'candidates.history' => ACCESS_LEVEL_DEMO,
            'joborders' => ACCESS_LEVEL_DELETE,
            'joborders.show' => ACCESS_LEVEL_DEMO,
            'joborders.email' => ACCESS_LEVEL_DISABLED,
        )
    );*/

**Comment by Albin4d** [comment]
I think that issue is solved - i've changed php to v5.6 and problem disappeared.

**Comment by TJEliot** [comment]
@Albin4d what did you do to resolve this? I'm getting the exact same error. I changed the version number from 5.5 to 5.6 in `docker-compose.yml` and `Dockerfile`, and I ran `docker-compose down`, `docker-compose build`, `docker-compose -d up` and I'm still getting the same result when going to `127.0.0.1/opencats/installwizard.php`, namely 

`Parse error: syntax error, unexpected '[' in /var/www/html/opencats/lib/ACL.php on line 61`
